### ISSUE TITLE
06 python打印出微信被删除好友 不能运行

### ISSUE THREAD

**Issue by Zhangxuri** [lb2281075105/Python-WeChat-ItChat#5]
1. 好多行缩进不对
2.改好缩进后运行报错
```
Traceback (most recent call last):
  File "/Users/zhangxuri/project/research/nlp/test/删除的好友/index.py", line 415, in <module>
    main()
  File "/Users/zhangxuri/project/research/nlp/test/删除的好友/index.py", line 336, in main
    if login() == False:
  File "/Users/zhangxuri/project/research/nlp/test/删除的好友/index.py", line 127, in login
    response = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: 
```

**Comment by mondayice** [comment]
我也是这样

**Comment by 543052377** [comment]
我的运行到“请使用微信扫描二维码以登录”，并没有弹出二维码，求指点
